name: Deploy Next.js site to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          static_site_generator: next

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        run: npm run build
        # Using default .next directory for build output

      - name: List directory contents for debugging
        run: |
          echo "Current directory:"
          ls -la
          echo ".next directory exists?"
          test -d ./.next && echo "Yes, .next directory exists" || echo "No, .next directory does not exist"
          if [ -d "./.next" ]; then
            echo "Contents of .next directory:"
            ls -la ./.next
          fi

      # Export the Next.js app to static HTML
      - name: Export Next.js app
        run: npx next export

      - name: List out directory after export
        run: |
          echo "out directory exists?"
          test -d ./out && echo "Yes, out directory exists" || echo "No, out directory does not exist"
          if [ -d "./out" ]; then
            echo "Contents of out directory:"
            ls -la ./out
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 