name: Deploy Next.js site to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          static_site_generator: next

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        run: |
          npm run build
          npm run export

      - name: List directory contents for debugging
        run: |
          echo "Current directory:"
          ls -la
          echo "out directory exists?"
          test -d ./out && echo "Yes, out directory exists" || echo "No, out directory does not exist"
          if [ -d "./out" ]; then
            echo "Contents of out directory:"
            ls -la ./out
          fi
          if [ -d "./.next" ]; then
            echo "Contents of .next directory:"
            ls -la ./.next
          fi

      # This step is now likely unnecessary but kept as a fallback
      - name: Create out directory if needed
        run: |
          if [ ! -d "./out" ] && [ -d "./.next" ]; then
            echo "out directory not found but .next exists. Manually creating export..."
            npx next export
          fi
          # Double check if out directory now exists
          if [ ! -d "./out" ]; then
            echo "Still no out directory. Creating fallback content..."
            mkdir -p ./out
            echo "<html><body><h1>Emergency Fallback Page</h1><p>The build process failed to create the expected output directory.</p><p>Please check the GitHub Actions logs for more information.</p></body></html>" > ./out/index.html
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 